GET http://fhirserver.hl7fundamentals.org/fhir/Patient/65216 HTTP/1.1
content-type: application/json

###

GET http://fhirserver.hl7fundamentals.org/fhir/Patient/65216 HTTP/1.1
content-type: application/xml

###

POST http://fhirserver.hl7fundamentals.org/fhir/Patient HTTP/1.1
content-type: application/fhir+json

{
    "resourceType": "Patient",
    "identifier": [
        {
            "value": "elpacific.binagha",
            "system": "https://hgr-virunga.cbcaoffice.org/patients"
        }
    ],
    "gender": "male",
    "birthDate": "1960-06-30",
    "name": [
        {
            "family": "Binagha",
            "given": [
                "El Pacific"
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "(03) 5555 6789",
            "use": "home"
        }
    ],
    "address": [
        {
            "line": [
                "3300 Washtenaw"
            ],
            "city": "Ann Harbor",
            "district": "Washtenaw",
            "state": "MI",
            "postalCode": "48104",
            "country": "US"
        }
    ]
}

###

POST http://fhirserver.hl7fundamentals.org/fhir HTTP/1.1
content-type: application/fhir+xml

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

PUT http://fhirserver.hl7fundamentals.org/fhir/Patient/65216 HTTP/1.1
content-type: application/fhir+json

{
    "resourceType": "Patient",
    "id": "65216",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2025-07-27T16:32:34.381+00:00",
        "source": "#Z5E5ikf8BclH1Xjq"
    },
    "identifier": [
        {
            "system": "https://hgr-virunga.cbcaoffice.org/patients",
            "value": "elpacific.binagha"
        }
    ],
    "name": [
        {
            "family": "Binagha",
            "given": [
                "El Pacific"
            ]
        }
    ],
    "telecom": [
        {
            "system": "phone",
            "value": "(243) 993 818 236",
            "use": "work"
        }
    ],
    "gender": "male",
    "birthDate": "1960-06-30",
    "address": [
        {
            "line": [
                "028 Nzumuka James"
            ],
            "city": "Goma",
            "district": "Nord-Kivu",
            "state": "DRC",
            "postalCode": "485",
            "country": "CD"
        }
    ]
}
